// blog/src/app/dynamics/page.tsx
import { getDynamics } from "@/lib/api";
export const dynamic = "force-dynamic";
import dayjs from "dayjs";
import { MessageCircle, Pin } from "lucide-react";
import { MotionDiv } from "@/components/Motion";

export default async function DynamicsPage() {
  let dynamics: any[] = [];
  try {
    const res = await getDynamics();
    dynamics = res.data || [];
  } catch {}

  return (
    <div className="pt-16 min-h-screen">
      <div className="max-w-2xl mx-auto px-6 py-16">
        <div className="flex items-center gap-3 mb-12">
          <MessageCircle className="w-6 h-6 text-aurora-500" />
          <h1 className="text-3xl font-bold font-serif text-gray-900">动态</h1>
        </div>

        {dynamics.length > 0 ? (
          <div className="space-y-6">
            {dynamics.map((dyn, i) => {
              let images: string[] = [];
              try { images = JSON.parse(dyn.images || "[]"); } catch {}
              return (
                <MotionDiv
                  key={dyn.id}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="rounded-2xl bg-white border border-gray-100 p-6 shadow-sm"
                >
                  {dyn.pinned && (
                    <div className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-aurora-50 text-aurora-500 text-xs mb-2">
                      <Pin className="w-3 h-3" /> 置顶
                    </div>
                  )}
                  <p className="text-gray-700 leading-relaxed whitespace-pre-wrap mb-3">{dyn.content}</p>
                  {images.length > 0 && (
                    <div className={`grid ${images.length > 1 ? "grid-cols-2" : "grid-cols-1"} gap-2 mb-3`}>
                      {images.map((img, idx) => (
                        <img key={idx} src={img} alt="" className="rounded-xl w-full h-48 object-cover" />
                      ))}
                    </div>
                  )}
                  <span className="text-sm text-gray-400">{dayjs(dyn.published).format("YYYY-MM-DD HH:mm")}</span>
                </MotionDiv>
              );
            })}
          </div>
        ) : (
          <div className="text-center py-20 text-gray-400">暂无动态</div>
        )}
      </div>
    </div>
  );
}

// admin/src/views/Dynamics.vue
<template>
  <div class="space-y-4">
    <div class="flex items-center justify-between">
      <h2 class="text-xl font-semibold text-gray-800">动态管理</h2>
    </div>

    <!-- New Dynamic -->
    <div class="card p-4">
      <textarea v-model="newContent" placeholder="说点什么..." class="input h-24 resize-none mb-3"></textarea>
      <div class="flex items-center justify-between">
        <label class="flex items-center gap-2 text-sm text-gray-500">
          <input type="checkbox" v-model="newPinned" class="rounded" /> 置顶
        </label>
        <button @click="createDynamic" class="btn-primary" :disabled="!newContent.trim()">发布动态</button>
      </div>
    </div>

    <!-- List -->
    <div class="space-y-3">
      <div v-for="dyn in dynamics" :key="dyn.id" class="card p-4 animate-fade-up">
        <div class="flex items-start justify-between gap-4">
          <div class="flex-1">
            <div class="flex items-center gap-2 mb-1">
              <span v-if="dyn.pinned" class="text-aurora-500">📌</span>
              <p class="text-gray-700 whitespace-pre-wrap">{{ dyn.content }}</p>
            </div>
            <span class="text-xs text-gray-400">{{ formatDate(dyn.published) }}</span>
          </div>
          <button @click="deleteDynamic(dyn.id)" class="text-sm text-red-500 hover:text-red-600">删除</button>
        </div>
      </div>
      <div v-if="!dynamics.length" class="text-center py-12 text-gray-400">暂无动态</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import api from "@/api";
import dayjs from "dayjs";

const dynamics = ref<any[]>([]);
const newContent = ref("");
const newPinned = ref(false);

function formatDate(d: string) { return dayjs(d).format("YYYY-MM-DD HH:mm"); }

async function fetchDynamics() {
  try { const res = await api.get("/dynamics"); dynamics.value = res.data.data || []; } catch {}
}

async function createDynamic() {
  if (!newContent.value.trim()) return;
  try {
    await api.post("/dynamics", { content: newContent.value, pinned: newPinned.value });
    newContent.value = ""; newPinned.value = false;
    await fetchDynamics();
  } catch (e: any) { alert(e.response?.data?.error || "发布失败"); }
}

async function deleteDynamic(id: number) {
  if (!confirm("确定删除这条动态吗？")) return;
  try { await api.delete(`/dynamics/${id}`); await fetchDynamics(); } catch {}
}

onMounted(fetchDynamics);
</script>
