// blog/src/app/projects/page.tsx
import { getProjects } from "@/lib/api";
import { Folder, ExternalLink, Github, Star } from "lucide-react";
import { MotionDiv } from "@/components/Motion";
import Link from "next/link";
import dayjs from "dayjs";

export default async function ProjectsPage() {
  let projects: any[] = [];
  try {
    const res = await getProjects();
    projects = res.data || [];
  } catch {}

  return (
    <div className="pt-16 min-h-screen">
      <div className="max-w-6xl mx-auto px-6 py-16">
        <div className="flex items-center gap-3 mb-12">
          <Folder className="w-6 h-6 text-aurora-500" />
          <h1 className="text-3xl font-bold font-serif text-gray-900">项目</h1>
          <span className="text-gray-400 text-lg">({projects.length} 个)</span>
        </div>

        {projects.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {projects.map((project, i) => (
              <MotionDiv
                key={project.id}
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.1 }}
                className="card-hover group rounded-2xl bg-white border border-gray-100 overflow-hidden"
              >
                {project.coverImage && (
                  <div className="h-40 overflow-hidden">
                    <img src={project.coverImage} alt={project.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" />
                  </div>
                )}
                <div className="p-6">
                  <div className="flex items-center gap-2 mb-2">
                    <h3 className="text-xl font-bold font-serif text-gray-900 group-hover:text-aurora-600 transition-colors">{project.title}</h3>
                    {project.featured && <Star className="w-4 h-4 text-yellow-400 fill-yellow-400" />}
                  </div>
                  <p className="text-sm text-gray-500 mb-4 line-clamp-2">{project.description}</p>
                  {project.techStack?.length > 0 && (
                    <div className="flex flex-wrap gap-2 mb-4">
                      {project.techStack.map((tech: string) => (
                        <span key={tech} className="px-2.5 py-1 rounded-md bg-aurora-50 text-aurora-600 text-xs font-medium">{tech}</span>
                      ))}
                    </div>
                  )}
                  <div className="flex items-center gap-3">
                    {project.demoUrl && (
                      <a href={project.demoUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-sm text-aurora-600 hover:text-aurora-700">
                        <ExternalLink className="w-4 h-4" /> Demo
                      </a>
                    )}
                    {project.repoUrl && (
                      <a href={project.repoUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-sm text-gray-500 hover:text-gray-700">
                        <Github className="w-4 h-4" /> Source
                      </a>
                    )}
                    <span className="text-xs text-gray-400 ml-auto">{dayjs(project.published).format("YYYY-MM")}</span>
                  </div>
                </div>
              </MotionDiv>
            ))}
          </div>
        ) : (
          <div className="text-center py-20 text-gray-400">暂无项目</div>
        )}
      </div>
    </div>
  );
}

// admin/src/views/Projects.vue
<template>
  <div class="space-y-4">
    <div class="flex items-center justify-between">
      <h2 class="text-xl font-semibold text-gray-800">项目管理</h2>
      <button @click="showForm = !showForm" class="btn-primary">{{ showForm ? "取消" : "➕ 添加项目" }}</button>
    </div>

    <!-- Form -->
    <div v-if="showForm" class="card p-6 space-y-4 animate-fade-up">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <input v-model="form.title" placeholder="项目名称" class="input" />
        <input v-model="form.slug" placeholder="Slug (选填)" class="input" />
      </div>
      <textarea v-model="form.description" placeholder="项目描述" class="input h-20 resize-none"></textarea>
      <input v-model="form.coverImage" placeholder="封面图片 URL" class="input" />
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <input v-model="form.demoUrl" placeholder="Demo URL" class="input" />
        <input v-model="form.repoUrl" placeholder="仓库 URL" class="input" />
      </div>
      <input v-model="techInput" placeholder="技术栈（逗号分隔）" class="input" />
      <div class="flex items-center gap-4">
        <label class="flex items-center gap-2 text-sm text-gray-500"><input type="checkbox" v-model="form.featured" class="rounded" /> 精选</label>
        <label class="flex items-center gap-2 text-sm text-gray-500"><input type="checkbox" v-model="form.draft" class="rounded" /> 草稿</label>
      </div>
      <button @click="createProject" class="btn-primary">保存项目</button>
    </div>

    <!-- List -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div v-for="project in projects" :key="project.id" class="card p-5 animate-fade-up">
        <div class="flex items-start justify-between mb-2">
          <h3 class="font-bold text-gray-800">{{ project.title }}</h3>
          <button @click="deleteProject(project.slug)" class="text-sm text-red-500 hover:text-red-600">删除</button>
        </div>
        <p class="text-sm text-gray-500 mb-3">{{ project.description }}</p>
        <div v-if="project.techStack?.length" class="flex flex-wrap gap-1 mb-3">
          <span v-for="tech in project.techStack" :key="tech" class="px-2 py-0.5 rounded text-xs bg-aurora-50 text-aurora-600">{{ tech }}</span>
        </div>
        <div class="flex gap-3 text-sm">
          <a v-if="project.demoUrl" :href="project.demoUrl" target="_blank" class="text-aurora-600">Demo →</a>
          <a v-if="project.repoUrl" :href="project.repoUrl" target="_blank" class="text-gray-500">Source →</a>
        </div>
      </div>
    </div>
    <div v-if="!projects.length" class="text-center py-12 text-gray-400">暂无项目</div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import api from "@/api";

const projects = ref<any[]>([]);
const showForm = ref(false);
const techInput = ref("");
const form = ref({ title: "", slug: "", description: "", coverImage: "", demoUrl: "", repoUrl: "", featured: false, draft: false });

async function fetchProjects() {
  try { const res = await api.get("/projects", { params: { draft: "true" } }); projects.value = res.data.data || []; } catch {}
}

async function createProject() {
  if (!form.value.title) return alert("请输入项目名称");
  try {
    await api.post("/projects", { ...form.value, techStack: techInput.value.split(",").map(s => s.trim()).filter(Boolean) });
    form.value = { title: "", slug: "", description: "", coverImage: "", demoUrl: "", repoUrl: "", featured: false, draft: false };
    techInput.value = ""; showForm.value = false;
    await fetchProjects();
  } catch (e: any) { alert(e.response?.data?.error || "创建失败"); }
}

async function deleteProject(slug: string) {
  if (!confirm("确定删除这个项目吗？")) return;
  try { await api.delete(`/projects/${slug}`); await fetchProjects(); } catch {}
}

onMounted(fetchProjects);
</script>
